---
title: "Why is life awsome?"
date: 2022-06-03
---
title: Life is awesome
author: honigbienlein
email: myemail@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Everything about good life. What does this mean? 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
